version: "3.8"

services:
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    environment:
      - POSTGRES_DB=saldo-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  pgweb:
    image: ghcr.io/sosedoff/pgweb:latest
    container_name: pgweb
    restart: always
    ports:
      - "54321:8081"
    environment:
      PGWEB_DATABASE_URL: "postgres://postgres:postgres@db:5432/saldo-db?sslmode=disable"
      PGWEB_LOCK_SESSION: true
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
